%%
%% vxi.hrl was generated by erpcgen (do not edit)
%% date: Nov 24 17:41:22 2014
%%
-define(DEVICE_ASYNC, 395184).
-define(DEVICE_ASYNC_VERSION, 1).
-define(DEVICE_CORE, 395183).
-define(DEVICE_CORE_VERSION, 1).
-define(DEVICE_INTR, 395185).
-define(DEVICE_INTR_VERSION, 1).
